from typing import Literal

from pydantic import BaseModel, Field


class SessionCreateRequest(BaseModel):
    """Defines the data required to create a new AI assistant session."""

    system_instruction: str = Field(
        description="The core instruction that defines the AI's role and behavior.",
        examples=[
            "You are a helpful assistant for our financial software. Guide the user through creating an invoice."
        ],
    )
    audio_speaker_name: str = Field(
        default="Zephyr",
        description="The prebuilt voice name for the AI's spoken responses.",
    )
    target_fps: int = Field(
        default=10,
        ge=1,
        le=30,
        description="Target frames per second for the video stream.",
    )
    jpeg_quality: int = Field(
        default=75, ge=1, le=95, description="Compression quality for the video frames."
    )


class SdpPayload(BaseModel):
    """A standard model for Session Description Protocol (SDP) payloads."""

    type: Literal["offer", "answer"]
    sdp: str


class SessionCreateResponse(BaseModel):
    """The response sent to the client after a session is successfully created."""

    session_id: str = Field(description="The unique identifier for the new session.")
    offer: SdpPayload = Field(
        description="The SDP offer from the server to initiate the WebRTC connection.",
    )


class SdpAnswerRequest(BaseModel):
    """The model for the client to send its SDP answer back to the server."""

    answer: SdpPayload = Field(description="The SDP answer generated by the client.")


class StatusResponse(BaseModel):
    """A generic response model for status updates."""

    status: str
    message: str | None = None
